### ISSUE TITLE
Is this project being actively developed still?

### ISSUE THREAD

**Issue by bsneed** [JohnEstropia/GCDKit#1]
Hi John,

I really like your GCDKit interfaces.  I'd like to make a few initial changes and additions.  Add GCD Timer support, etc.  We'll probably be making a lot of changes over the long haul that we're using it, but those are the immediate needs right now.  I don't want to burden you with change requests, or hi-jack your project, so my options are to either fork it, or adopt it and give it a new name (your name and license to remain intact of course).  Do you have any preference on this?

Thanks!

Brandon

**Comment by JohnEstropia** [comment]
I'm still using this library with my own projects so yes, I'm still maintaining this. The only reason I haven't added GCDTimer yet is only because I don't personally need it yet. It's trivial to create though, I can probably push a working prototype over the next few days.

I appreciate pull requests; Good ideas are welcome and I may have overlooked some use cases that might help everyone else in the future. Of course you're also free to fork and implement it as your own, I won't mind :)

**Comment by bsneed** [comment]
That's fantastic John.  Thanks so much.  I just pushed my first PR to you, and have a timer in progress.  I'm still somewhat new to swift and would like to try my hand at it, so if you had any ideas on the timer implementation you were thinking of and could share that's be great.  So far I'm kind of just exposing the GCD timer stuff directly but I really love how you managed to do all the chaining with the other things like GCDBlock and GCDQueue.  If there's anything along those lines you've come up with, I'm all ears.
